### ISSUE TITLE
Simplify using generic associated types (GAT)

### ISSUE THREAD

**Issue by KonradHoeffner** [pchampin/sophia_rs#126]
There are some mentions of possible simplifications of the API using generic associated types, which are stable since Rust 1.65, so I think this could be started now.

**Comment by pchampin** [comment]
Yes, I'm on it. I'll try to find some time during the mid-winter break to make an alpha release...

**Comment by pchampin** [comment]
Finally there! Not released on crates.io yet, but you can try it out with
```toml
[dependencies]
sophia = { version="0.8.0-alpha", git="https://github.com/pchampin/sophia_rs" }
```
I have documented the most significant changes there:
https://github.com/pchampin/sophia_rs
